modified the church marketing site text
faith-forward/marketing-site pull request #1
Opened 2023-07-15 03:43 UTC by ParkerP98

2023-07-19 16:13 UTC, phrazzld approved these changes

2023-07-22 18:06 UTC, jacogrande requested changes

2023-07-22 18:06 UTC, jacogrande commented on src/routes/churches/features/desk.svelte
> +				"Optimize your publishing process with Faith Forward's Writing Desk. From crafting to scheduling to delivering, push meaningful content directly to your congregation's feeds with ease.",
Each of these descriptions kind of start with a subtitle which gets funky when the item already has a subtitle ("Optimize content delivery for your congregation. \n Optimize your publishing process with Faith Forward's Writing Desk" is a little awkward) I'd just take out the first sentence of each of them.

2023-07-22 22:20 UTC, jacogrande approved these changes

2023-07-22 22:21 UTC, merged